<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // データのクリア
        DB::table('Users')->truncate();
        // データの作成
        DB::table('Users')->insert([
            [
                'id'                  => '000101',
                'name'                => 'ALFA',
                'email'               => 'ALFA@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('ALFA'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000102',
                'name'                => 'BRAVO',
                'email'               => 'BRAVO@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('BRAVO'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000103',
                'name'                => 'CHARLIE',
                'email'               => 'CHARLIE@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('CHARLIE'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000104',
                'name'                => 'DELTA',
                'email'               => 'DELTA@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('DELTA'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000105',
                'name'                => 'ECHO',
                'email'               => 'ECHO@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('ECHO'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000106',
                'name'                => 'FOXTROT',
                'email'               => 'FOXTROT@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('FOXTROT'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000107',
                'name'                => 'GOLF',
                'email'               => 'GOLF@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('GOLF'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000108',
                'name'                => 'HOTEL',
                'email'               => 'HOTEL@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('HOTEL'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000109',
                'name'                => 'INDIA',
                'email'               => 'INDIA@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('INDIA'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000110',
                'name'                => 'JULIETT',
                'email'               => 'JULIETT@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('JULIETT'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000111',
                'name'                => 'KILO',
                'email'               => 'KILO@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('KILO'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000112',
                'name'                => 'LIMA',
                'email'               => 'LIMA@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('LIMA'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000113',
                'name'                => 'MIKE',
                'email'               => 'MIKE@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('MIKE'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000114',
                'name'                => 'NOVEMBER',
                'email'               => 'NOVEMBER@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('NOVEMBER'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000115',
                'name'                => 'OSCAR',
                'email'               => 'OSCAR@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('OSCAR'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000116',
                'name'                => 'PAPA',
                'email'               => 'PAPA@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('PAPA'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000117',
                'name'                => 'QUEBEC',
                'email'               => 'QUEBEC@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('QUEBEC'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000118',
                'name'                => 'ROMEO',
                'email'               => 'ROMEO@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('ROMEO'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000119',
                'name'                => 'SIERRA',
                'email'               => 'SIERRA@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('SIERRA'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000120',
                'name'                => 'TANGO',
                'email'               => 'TANGO@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('TANGO'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000121',
                'name'                => 'UNIFORM',
                'email'               => 'UNIFORM@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('UNIFORM'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000122',
                'name'                => 'VICTOR',
                'email'               => 'VICTOR@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('VICTOR'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000123',
                'name'                => 'WHISKEY',
                'email'               => 'WHISKEY@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('WHISKEY'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000124',
                'name'                => 'X-RAY',
                'email'               => 'X-RAY@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('X-RAY'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000125',
                'name'                => 'YANKEE',
                'email'               => 'YANKEE@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('YANKEE'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ],
            [
                'id'                  => '000126',
                'name'                => 'ZULU',
                'email'               => 'ZULU@jast.co.jp',
                'email_verified_at'   => null,
                'password'            => Hash::make('ZULU'),
                'remember_token'      => null,
                'created_at'          => date('Y-m-d H:i:s'),
                'updated_at'          => null,
            ]
        ]);
    }
}
